### ISSUE TITLE
Preview em/strong as italic/bold

### ISSUE THREAD

**Issue by silopolis** [domdomegg/markdown-inline-preview-vscode#10]
Emphasized and strong texts are rendered as regular text. Having them adequately rendered as italic and bold, and combination of, would be nice.

Or is that a font choice issue ?

**Comment by domdomegg** [comment]
This sounds like it might be a font choice issue - italic and bold are supported by default I think.

Can you give an example document and screenshots that show it's not working for you, plus let me know what font you're using?

**Comment by silopolis** [comment]
Hey, thanks for your quick answer :pray: 

Meanwhile, went back to readme to see that this should indeed be working... Thus, added the suggested settings to switch editor to Fira when editing MD files, but this doesn't solve my rendering issue:

* Victor Mono NerdFont Mono

  ![Victor Mono NerdFont Mono](https://github.com/domdomegg/markdown-inline-preview-vscode/assets/414540/c0495795-e353-47e2-8816-54a0a3bade52)

* Fira sans

  ![Fira sans](https://github.com/domdomegg/markdown-inline-preview-vscode/assets/414540/4b527fee-c800-4f9d-82c4-c55f0c5857d6)

**Comment by domdomegg** [comment]
Can you provide the underlying markdown code for this as well?

**Comment by silopolis** [comment]
Sure

```
# Test markdown inline rendering

*This is em/italic*

**This is strong/bold**
```

**Comment by domdomegg** [comment]
That's odd - this works using VSCode's default styles (you can try on vscode.dev). I think something in your config or other extensions must be overriding this: try disabling different parts to identify what.

If you are able to repro this as a bug let me know though.
