### ISSUE TITLE
Add setting/command to toggle for colored/monochrome

### ISSUE THREAD

**Issue by silopolis** [domdomegg/markdown-inline-preview-vscode#9]
If I understand the taste for slick, non-distracting, monochrome style for writers, colors are a great help for structured/technical writing.
Also, both styles may be helpful for any writer/note-taker at different stages of the writing process.

Consequently, a toggle for switching between the two modes would be a great addition.

**Comment by domdomegg** [comment]
This plugin doesn't change the colors directly. The recommended `.vscode/settings.json` does, but this is just leveraging VS Code's built-in theming: you can edit `editor.tokenColorCustomizations` there to alter colors.
